"""initial migration

Revision ID: 5a198d1d550c
Revises: 
Create Date: 2025-12-01 16:05:51.521571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a198d1d550c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_id'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_username'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_index(op.f('ix_Items_id'), table_name='Items')
    op.drop_index(op.f('ix_Items_title'), table_name='Items')
    op.drop_table('Items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Items_title'), 'Items', ['title'], unique=False)
    op.create_index(op.f('ix_Items_id'), 'Items', ['id'], unique=False)
    op.create_table('Usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Usuarios_username'), 'Usuarios', ['username'], unique=1)
    op.create_index(op.f('ix_Usuarios_id'), 'Usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=1)
    # ### end Alembic commands ###
